version: "3.9"

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tuestecafe
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/app:/app/app
      - ./backend/.env:/app/.env:ro
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/tuestecafe
      SECRET_KEY: super-secret-key
      ACCESS_TOKEN_EXPIRE_MINUTES: 1440
      FIRST_SUPERUSER_EMAIL: admin@caturro.cafe
      FIRST_SUPERUSER_PASSWORD: admin123
    networks:
      - internal

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    command: npm run dev -- --host 0.0.0.0 --port 5173
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      VITE_API_URL: /api
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - backend
    networks:
      - internal

  adminer:
    image: adminer:4.8.1
    depends_on:
      - db
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
      - internal

  nginx:
    image: nginx:alpine
    depends_on:
      - frontend
      - backend
      - adminer
    ports:
      - "3010:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - internal
      - proxy

volumes:
  postgres_data:

networks:
  internal:
    driver: bridge
    internal: true
  proxy:
    driver: bridge
