version: "3.9"

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tuestecafe
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/app:/app/app
      - ./backend/.env:/app/.env:ro
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/tuestecafe
      SECRET_KEY: super-secret-key
      ACCESS_TOKEN_EXPIRE_MINUTES: 1440
      FIRST_SUPERUSER_EMAIL: admin@caturro.cafe
      FIRST_SUPERUSER_PASSWORD: admin123
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    command: npm run dev -- --host 0.0.0.0 --port 5173
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      VITE_API_URL: http://localhost:8000
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  postgres_data:
